[2023-11-05 23:27:21,116] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: split_excel_to_s3.read_excel manual__2023-11-05T23:27:11.218823+00:00 [queued]>
[2023-11-05 23:27:21,131] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: split_excel_to_s3.read_excel manual__2023-11-05T23:27:11.218823+00:00 [queued]>
[2023-11-05 23:27:21,132] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-11-05 23:27:21,132] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-11-05 23:27:21,132] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-11-05 23:27:21,151] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): read_excel> on 2023-11-05 23:27:11.218823+00:00
[2023-11-05 23:27:21,157] {standard_task_runner.py:52} INFO - Started process 916 to run task
[2023-11-05 23:27:21,161] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'split_excel_to_s3', 'read_excel', 'manual__2023-11-05T23:27:11.218823+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/write_xlsx_to_csv_s3.py', '--cfg-path', '/tmp/tmps6mxb9kt', '--error-file', '/tmp/tmp1leq_t6t']
[2023-11-05 23:27:21,162] {standard_task_runner.py:80} INFO - Job 57: Subtask read_excel
[2023-11-05 23:27:21,247] {task_command.py:371} INFO - Running <TaskInstance: split_excel_to_s3.read_excel manual__2023-11-05T23:27:11.218823+00:00 [running]> on host 59b74f6ac638
[2023-11-05 23:27:21,346] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=split_excel_to_s3
AIRFLOW_CTX_TASK_ID=read_excel
AIRFLOW_CTX_EXECUTION_DATE=2023-11-05T23:27:11.218823+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-05T23:27:11.218823+00:00
[2023-11-05 23:27:21,576] {xcom.py:586} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2023-11-05 23:27:21,577] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/write_xlsx_to_csv_s3.py", line 34, in read_excel
    kwargs['ti'].xcom_push(key='dataframe', value=combined_df)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2412, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 198, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 583, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-11-05 23:27:21,588] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=split_excel_to_s3, task_id=read_excel, execution_date=20231105T232711, start_date=20231105T232721, end_date=20231105T232721
[2023-11-05 23:27:21,600] {standard_task_runner.py:97} ERROR - Failed to execute job 57 for task read_excel (Object of type DataFrame is not JSON serializable; 916)
[2023-11-05 23:27:21,615] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-05 23:27:21,664] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
